{
 "title": "PINGO DC-to-DC",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "Source",
    "query": {
     "query": "label_values(udp_received_total{job=~\"netops_pingo_exporter|netops-pingo\"}, dc)"
    }
   },
   {
    "name": "DestinationDC",
    "query": {
     "query": "label_values(udp_sent_total{dc=\"$Source\"}, dst_dc)"
    }
   },
   { "name": "resolution", "query": "1m,2m,5m,10m,30m" },
   {
    "name": "FPBR",
    "query": {
     "query": "label_values(udp_sent_total{dc=\"$Source\", dst_dc=\"$DestinationDC\", pbr!=\"CURRENT\"}, pbr)"
    }
   },
   {
    "name": "RPBR",
    "query": {
     "query": "label_values(udp_sent_total{dc=\"$Source\", dst_dc=\"$DestinationDC\", rpbr!=\"CURRENT\"}, rpbr)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Path Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CURRENT/CURRENT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(udp_latency_quantile{dc=\"$Source\",dst_dc=\"$DestinationDC\", pbr=\"CURRENT\", rpbr=\"CURRENT\", pct!~\"avg|0\"}) by (pbr, rpbr, target, pct)",
     "legendFormat": "{{pct}}"
    },
    {
     "expr": "udp:worst_current_stream_loss:$resolution{dc=\"$Source\",dst_dc=\"$DestinationDC\"}",
     "legendFormat": "packetloss"
    },
    {
     "expr": "count(avg(increase(udp_received_total{dc=\"$Source\",dst_dc=\"$DestinationDC\", pbr=\"CURRENT\", rpbr=\"CURRENT\"}[$resolution])/increase(udp_sent_total{dc=\"$Source\",dst_dc=\"$DestinationDC\", pbr=\"CURRENT\", rpbr=\"CURRENT\"}[$resolution])) by (target,lport,rport) < 1)",
     "legendFormat": "lossy count"
    },
    {
     "expr": "udp_current_transit_path{dc=\"$Source\", dst_dc=\"$DestinationDC\", seq=\"0\"}",
     "legendFormat": "Forward Path"
    },
    {
     "expr": "udp_current_transit_path{dc=\"$DestinationDC\", dst_dc=\"$Source\", seq=\"0\"}",
     "legendFormat": "Reverse Path"
    }
   ]
  },
  {
   "title": "$RPBR - LLS % Improvement relative to current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "udp:provider:loss_latency_score:$resolution{dc=\"$Source\",dst_dc=\"$DestinationDC\"} / ignoring (pbr, rpbr) group_left(dc, dst_dc) udp:provider:loss_latency_score:$resolution{dc=\"$Source\",dst_dc=\"$DestinationDC\", pbr=\"CURRENT\", rpbr=\"CURRENT\"} -1",
     "legendFormat": "{{pbr}} - {{rpbr}}"
    },
    {}
   ]
  },
  {
   "title": "Fwd",
   "type": "table",
   "gridPos": { "h": 6, "w": 1, "x": 22, "y": 1 },
   "targets": [
    {
     "expr": "udp_current_transit_path{dc=\"$Source\", dst_dc=\"$DestinationDC\"} > 0"
    }
   ]
  },
  {
   "title": "Resp",
   "type": "table",
   "gridPos": { "h": 6, "w": 1, "x": 23, "y": 1 },
   "targets": [
    {
     "expr": "udp_current_transit_path{dc=\"$DestinationDC\", dst_dc=\"$Source\"} > 0"
    }
   ]
  },
  {
   "title": "$Source to $DestinationDC via $FPBR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "FPBR"
  },
  {
   "title": "${FPBR}",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "style=\"background-color: #FCFCFC;\""
   }
  },
  {
   "title": "$DestinationDC to $Source via $RPBR ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "repeat": "RPBR",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(udp_latency_quantile{dc=\"$Source\",dst_dc=\"$DestinationDC\", pbr=\"$FPBR\", rpbr=\"$RPBR\", pct!~\"avg|0\"}) by (pbr, rpbr, target, pct)",
     "legendFormat": "{{pct}}"
    },
    {
     "expr": "udp:worst_pbr_stream_loss:$resolution{dc=\"$Source\",dst_dc=\"$DestinationDC\",pbr=\"$FPBR\", rpbr=\"$RPBR\"}",
     "legendFormat": "packetloss"
    },
    {
     "expr": "count(avg(increase(udp_received_total{dc=\"$Source\",dst_dc=\"$DestinationDC\", pbr=\"$FPBR\", rpbr=\"$RPBR\"}[$resolution])/increase(udp_sent_total{dc=\"$Source\",dst_dc=\"$DestinationDC\", pbr=\"$FPBR\", rpbr=\"$RPBR\"}[$resolution])) by (target,lport,rport) < 1)",
     "legendFormat": "lossy flow count"
    }
   ]
  }
 ]
}